# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/oscar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oscar)

$(call add-radio-file-sha1-checked,radio/abl.img,7466cd7cafa207381c6c5aa88346cb66973df14b)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,454d08ab8597706eb61a1e281be2257f710466fa)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,2a185350ee531180e63674139a5e78ed80183dbb)
$(call add-radio-file-sha1-checked,radio/devcfg.img,44ab2eff7cd44ef33184ac516c9f0d5c933e6bed)
$(call add-radio-file-sha1-checked,radio/dsp.img,b1512787b130b7f9907aab41a05e471db8452675)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,d90d0729216cc90f2aa6d8a25f3ad45a40bc4647)
$(call add-radio-file-sha1-checked,radio/hyp.img,22cf4dfec1992de496343db3fa1fc6a6d15b8551)
$(call add-radio-file-sha1-checked,radio/imagefv.img,695060c7c81e59dc88f547cf28e2ff42e3c59bb4)
$(call add-radio-file-sha1-checked,radio/keymaster.img,5124a1e2ccd7a1be0b0f80d55bb7aa678008a273)
$(call add-radio-file-sha1-checked,radio/modem.img,6748f1c2a6335f58a52edb99e5c0fc044322c42f)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,cb3370fa73a12418926dddd90223c0628e6f3bc0)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0de737afee09180587e66a3037bcd8503cd4fc3f)
$(call add-radio-file-sha1-checked,radio/rpm.img,db8f396a2b1bfeb366269a28d77c5a704d35acb5)
$(call add-radio-file-sha1-checked,radio/splash.img,88b02f550aa70d1d51f8197ee83eb026c49f28e2)
$(call add-radio-file-sha1-checked,radio/tz.img,2def02995b2c1b2659d29d36467e535aa8c6b2c0)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,c1e82b7fc31a98d9c40e48fcc3f8a0962b475f68)
$(call add-radio-file-sha1-checked,radio/xbl.img,dbc1f293e63822a203cfd381d1ba9490d66f7c24)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,2510a93f9517edd80ca8d568b9e15cf32a0db71e)

endif
