# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/oscar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oscar)

$(call add-radio-file-sha1-checked,radio/abl.img,b8a51daab52bed22534b85e3e2f3fed2a950eb59)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,086ac08dbb92735c96759c0c97e11e8379e9938a)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,c09e5f14f7e0348a4551761108309bb5b2383233)
$(call add-radio-file-sha1-checked,radio/devcfg.img,bd411db1aa5493477973a9421b56463141394049)
$(call add-radio-file-sha1-checked,radio/dsp.img,9606e98a9e1a1b886170e4858e7dc5ab2910548a)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,135b11376a25c77fda7e92b1caba64d18e100440)
$(call add-radio-file-sha1-checked,radio/hyp.img,2ac0ec03e274beb88598d75ae6f1d658e6d993b3)
$(call add-radio-file-sha1-checked,radio/imagefv.img,9f791651eab6d8f907275a27052fe0099081ab2b)
$(call add-radio-file-sha1-checked,radio/keymaster.img,d4e11bde12ad91ba49297b73f984372fbe82dbc3)
$(call add-radio-file-sha1-checked,radio/modem.img,5171368eea32e2da996a2aa564d08cdfa5cccd37)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,8563984efab5c2c2b867ce1617c20a13053b08b3)
$(call add-radio-file-sha1-checked,radio/qupfw.img,9148490548b293ec6b62cc70e0c68f8ccc296cc7)
$(call add-radio-file-sha1-checked,radio/rpm.img,a3cf7c338a7ae62134b55d6d036d826c85ea9893)
$(call add-radio-file-sha1-checked,radio/splash.img,88b02f550aa70d1d51f8197ee83eb026c49f28e2)
$(call add-radio-file-sha1-checked,radio/tz.img,0999b8f942048886b5d3b082bb8ee0505b957067)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,6e12ad6ff08b48af1590f7d42e41402d7e04b1a9)
$(call add-radio-file-sha1-checked,radio/xbl.img,87d0f322c4286434b3741e7638a2ea7bd364d532)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,27a81b4891cad2af17da10a632b75bf543bd5f67)

endif
