# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/oscar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oscar)

$(call add-radio-file-sha1-checked,radio/abl.img,4bf81fd8126f56d5961ea54dfdc1dec3d8824b37)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,b83baa21f0a162011a96088a350eca395fae5851)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,e069a52fd46b6ebe8f722f216a82008316c548b0)
$(call add-radio-file-sha1-checked,radio/devcfg.img,b5901dab871ef6085cf880d918b0187e462522c7)
$(call add-radio-file-sha1-checked,radio/dsp.img,9606e98a9e1a1b886170e4858e7dc5ab2910548a)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,dd376c45b6a91a58e92387d46211c9a85433027e)
$(call add-radio-file-sha1-checked,radio/hyp.img,9c729a55cf4bc1dff39da9ff38a5cf53404797f4)
$(call add-radio-file-sha1-checked,radio/imagefv.img,74e2276d3a1ebc95bd1ce9ec7399b2de2e0d5964)
$(call add-radio-file-sha1-checked,radio/keymaster.img,49e27d91acef0eb730414742a0e79189f74d8b30)
$(call add-radio-file-sha1-checked,radio/modem.img,638111031066a260d0da0fcb674fafcd12b7afc9)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,c053a9a963e3cdb94d06e2d3290873f32caba439)
$(call add-radio-file-sha1-checked,radio/qupfw.img,80310eefcc763cae5ea76226c5839e1a5952a419)
$(call add-radio-file-sha1-checked,radio/rpm.img,bb24b4adad8f2a196bdd1ee91450de381e0e4425)
$(call add-radio-file-sha1-checked,radio/splash.img,88b02f550aa70d1d51f8197ee83eb026c49f28e2)
$(call add-radio-file-sha1-checked,radio/tz.img,474abeeff42ca6710fe0a8963a5d85660689c875)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,936fec155436dc1d4555ec5cead4bf6112f6e9a6)
$(call add-radio-file-sha1-checked,radio/xbl.img,fae196c203ba65334a12cd5754599d55b0b410dc)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,952cf5e8a3712ecbd0ed4485ea50567e8ed90330)

endif
