# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/oscar/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    bluetooth \
    core_nhlos \
    devcfg \
    dsp \
    engineering_cdt \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    oplus_sec \
    oplusstanvbk \
    qupfw \
    rpm \
    splash \
    tz \
    uefisecapp \
    xbl \
    xbl_config
